export default {
  // Global
  INITIALISE_STORE: 'INITIALISE_STORE',
  EXTRACT_TOKEN: 'EXTRACT_TOKEN',
  TOKEN_CHANGED: 'TOKEN_CHANGED',
  TOKEN_EXTRACTED: 'TOKEN_EXTRACTED',
  DO_LOGOUT: 'DO_LOGOUT',
  // Login
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  DO_LOGIN: 'DO_LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  SIGN_UP: 'SIGN_UP'
}
